apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: nginx-service-monitor
  namespace: nginx
spec:
  selector:
    matchLabels:
      app: nginx-service
  namespaceSelector:
    matchNames:
      - nginx
  endpoints:
  - port: web
