apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/ignore: "true"
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 58.1.0
    argocd.argoproj.io/instance: kube-prometheus-stack
    chart: kube-prometheus-stack-58.1.0
    heritage: Helm
    release: kube-prometheus-stack
    self-monitor: "true"
  name: kube-prometheus-stack-prometheus-np
  namespace: prometheus
spec:
  ports:
  - name: http-web
    nodePort: 32284
    port: 9090
    protocol: TCP
    targetPort: 9090
  - appProtocol: http
    name: reloader-web
    nodePort: 31061
    port: 8080
    protocol: TCP
    targetPort: reloader-web
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: kube-prometheus-stack-prometheus
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/ignore: "true"
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 10.4.0
    argocd.argoproj.io/instance: kube-prometheus-stack
    helm.sh/chart: grafana-7.3.7
  name: kube-prometheus-stack-grafana-np
  namespace: prometheus
spec:
  ports:
  - name: http-web
    nodePort: 31273
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}


---

# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
kind: Service
metadata:
  labels:
    argocd.argoproj.io/ignore: "true"
    app: kube-prometheus-stack-alertmanager
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 58.1.0
    argocd.argoproj.io/instance: kube-prometheus-stack
    chart: kube-prometheus-stack-58.1.0
    heritage: Helm
    release: kube-prometheus-stack
    self-monitor: "true"
  name: kube-prometheus-stack-alertmanager-np
  namespace: prometheus
spec:
  ports:
  - name: http-web
    nodePort: 31544
    port: 9093
    protocol: TCP
    targetPort: 9093
  - appProtocol: http
    name: reloader-web
    nodePort: 30315
    port: 8080
    protocol: TCP
    targetPort: reloader-web
  selector:
    alertmanager: kube-prometheus-stack-alertmanager
    app.kubernetes.io/name: alertmanager
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
