apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx
  labels:
    app: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - name: web
      port: 80
      targetPort: 80
      nodePort: 32600
      protocol: TCP
  type: NodePort
